# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 271))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_student_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.select_student_button.setFont(font)
        self.select_student_button.setMouseTracking(False)
        self.select_student_button.setTabletTracking(False)
        self.select_student_button.setAcceptDrops(False)
        self.select_student_button.setObjectName("select_student_button")
        self.verticalLayout.addWidget(self.select_student_button)
        self.select_words_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.select_words_button.setFont(font)
        self.select_words_button.setMouseTracking(False)
        self.select_words_button.setTabletTracking(False)
        self.select_words_button.setAcceptDrops(False)
        self.select_words_button.setObjectName("select_words_button")
        self.verticalLayout.addWidget(self.select_words_button)
        self.statistical_word_frequency_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.statistical_word_frequency_button.setFont(font)
        self.statistical_word_frequency_button.setMouseTracking(False)
        self.statistical_word_frequency_button.setTabletTracking(False)
        self.statistical_word_frequency_button.setAcceptDrops(False)
        self.statistical_word_frequency_button.setObjectName("statistical_word_frequency_button")
        self.verticalLayout.addWidget(self.statistical_word_frequency_button)
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(210, 10, 905, 705))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.right_frame.setFont(font)
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.left_show_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.left_show_text_browser.setGeometry(QtCore.QRect(15, 301, 181, 401))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.left_show_text_browser.setFont(font)
        self.left_show_text_browser.setObjectName("left_show_text_browser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.select_student_button.setText(_translate("MainWindow", "随机点名"))
        self.select_words_button.setText(_translate("MainWindow", "随机单词"))
        self.statistical_word_frequency_button.setText(_translate("MainWindow", "统计词频"))
