# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class select_words_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.show_words = QtWidgets.QTextBrowser(Form)
        self.show_words.setGeometry(QtCore.QRect(30, 20, 841, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_words.setFont(font)
        self.show_words.setObjectName("show_words")
        self.load_words = QtWidgets.QPushButton(Form)
        self.load_words.setGeometry(QtCore.QRect(450, 540, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_words.setFont(font)
        self.load_words.setObjectName("load_words")
        self.greate_random_words = QtWidgets.QPushButton(Form)
        self.greate_random_words.setGeometry(QtCore.QRect(730, 530, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.greate_random_words.setFont(font)
        self.greate_random_words.setAutoFillBackground(False)
        self.greate_random_words.setObjectName("greate_random_words")
        self.select_chapter_words = QtWidgets.QComboBox(Form)
        self.select_chapter_words.setGeometry(QtCore.QRect(40, 540, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_chapter_words.setFont(font)
        self.select_chapter_words.setObjectName("select_chapter_words")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(610, 520, 111, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.English_words_num = QtWidgets.QLineEdit(self.widget)
        # self.English_words_num.setText("")
        # self.English_words_num.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.English_words_num.setPlaceholderText("默认英文单词数量：10")
        self.English_words_num.setObjectName("English_words_num")
        self.verticalLayout.addWidget(self.English_words_num)
        self.chinese_words_num = QtWidgets.QLineEdit(self.widget)
        # self.chinese_words_num.setText("")
        self.chinese_words_num.setPlaceholderText("默认中文单词数量：0")
        self.chinese_words_num.setObjectName("chinese_words_num")
        self.verticalLayout.addWidget(self.chinese_words_num)
        self.update_words_chapter = QtWidgets.QPushButton(Form)
        self.update_words_chapter.setGeometry(QtCore.QRect(250, 540, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.update_words_chapter.setFont(font)
        self.update_words_chapter.setObjectName("update_words_chapter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_words.setText(_translate("Form", "导入新单词"))
        self.greate_random_words.setText(_translate("Form", "生成随机单词"))
        self.update_words_chapter.setText(_translate("Form", "更新单词列表"))
