# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_student_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class select_student_name_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.update_select_student_class_button = QtWidgets.QPushButton(Form)
        self.update_select_student_class_button.setGeometry(QtCore.QRect(220, 490, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.update_select_student_class_button.setFont(font)
        self.update_select_student_class_button.setObjectName("update_select_student_class_button")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(40, 40, 791, 401))
        self.textBrowser.setObjectName("textBrowser")
        self.start_select_student = QtWidgets.QPushButton(Form)
        self.start_select_student.setGeometry(QtCore.QRect(460, 490, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_select_student.setFont(font)
        self.start_select_student.setObjectName("start_select_student")
        self.stop_select_student = QtWidgets.QPushButton(Form)
        self.stop_select_student.setGeometry(QtCore.QRect(650, 490, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop_select_student.setFont(font)
        self.stop_select_student.setObjectName("stop_select_student")
        self.select_student_class_combox = QtWidgets.QComboBox(Form)
        self.select_student_class_combox.setGeometry(QtCore.QRect(40, 490, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_student_class_combox.setFont(font)
        self.select_student_class_combox.setObjectName("select_student_class_combox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.update_select_student_class_button.setText(_translate("Form", "更新班级名单"))
        self.start_select_student.setText(_translate("Form", "START"))
        self.stop_select_student.setText(_translate("Form", "STOP"))
