# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class select_words_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.show_words = QtWidgets.QTextBrowser(Form)
        self.show_words.setGeometry(QtCore.QRect(30, 20, 841, 421))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.show_words.setFont(font)
        self.show_words.setObjectName("show_words")

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(110, 480, 591, 151))
        self.widget.setObjectName("widget")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.select_chapter_words = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_chapter_words.setFont(font)
        self.select_chapter_words.setObjectName("select_chapter_words")
        self.horizontalLayout_2.addWidget(self.select_chapter_words)

        self.load_words = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_words.setFont(font)
        self.load_words.setObjectName("load_words")

        self.horizontalLayout_2.addWidget(self.load_words)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(70, 30, 30, 30)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.English_words_num = QtWidgets.QLineEdit(self.widget)
        self.English_words_num.setPlaceholderText("默认英文单词数量：10")
        # self.English_words_num.setObjectName("English_words_num")
        self.verticalLayout.addWidget(self.English_words_num)
        self.chinese_words_num = QtWidgets.QLineEdit(self.widget)
        self.chinese_words_num.setPlaceholderText("默认中文单词数量：0")
        self.verticalLayout.addWidget(self.chinese_words_num)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.greate_random_words = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.greate_random_words.setFont(font)
        self.greate_random_words.setAutoFillBackground(False)
        self.greate_random_words.setObjectName("greate_random_words")
        self.horizontalLayout.addWidget(self.greate_random_words)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select_chapter_words.setText(_translate("Form", "选择单元单词"))
        self.load_words.setText(_translate("Form", "导入新单词"))
        # self.English_words_num.setText(_translate("Form", "英文单词数量"))
        # self.chinese_words_num.setText(_translate("Form", "中文单词数量"))
        self.greate_random_words.setText(_translate("Form", "生成随机单词"))
