# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistical_word_frequency.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class statistical_word_frequency_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 851, 461))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.show_image_text_Browser = QtWidgets.QTextBrowser(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_image_text_Browser.setFont(font)
        self.show_image_text_Browser.setObjectName("show_image_text_Browser")
        self.horizontalLayout_2.addWidget(self.show_image_text_Browser)
        self.show_word_frequency = QtWidgets.QTextBrowser(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_word_frequency.setFont(font)
        self.show_word_frequency.setObjectName("show_word_frequency")
        self.horizontalLayout_2.addWidget(self.show_word_frequency)
        self.horizontalLayout_2.setStretch(0, 7)
        self.statistical_word_frequency = QtWidgets.QPushButton(Form)
        self.statistical_word_frequency.setGeometry(QtCore.QRect(330, 500, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statistical_word_frequency.setFont(font)
        self.statistical_word_frequency.setObjectName("statistical_word_frequency")
        self.select_test_paper = QtWidgets.QPushButton(Form)
        self.select_test_paper.setGeometry(QtCore.QRect(30, 500, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.select_test_paper.setFont(font)
        self.select_test_paper.setObjectName("select_test_paper")
        self.save_word_fre_result = QtWidgets.QPushButton(Form)
        self.save_word_fre_result.setGeometry(QtCore.QRect(660, 500, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_word_fre_result.setFont(font)
        self.save_word_fre_result.setAutoFillBackground(False)
        self.save_word_fre_result.setObjectName("save_word_fre_result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.show_image_text_Browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">show images</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))
        self.show_word_frequency.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">show word Frequency</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt;\"><br /></p></body></html>"))
        self.statistical_word_frequency.setText(_translate("Form", "统计词频"))
        self.select_test_paper.setText(_translate("Form", "选择图片或者文件夹"))
        self.save_word_fre_result.setText(_translate("Form", "保存结果"))
